### ISSUE TITLE
Support Elm 0.19

### ISSUE THREAD

**Issue by Pilatch** [virasak/angular-elm#5]
I'll make it happen... gimmie a couple days.

**Comment by Pilatch** [comment]
I have this implemented, but it's definitely a breaking change. I'm considering publishing it as my own repository if I don't hear back from you soon. That way I'll get it out to the wild sooner. I noticed that you haven't been active on Github for a while.

**Comment by virasak** [comment]
Hi, thank you for the update. You can publish it under your repo.

**Comment by Pilatch** [comment]
I recommend you update your readme to say that yours is Elm 0.18 compatible, to differentiate these two repositories. Closing issue!
